import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <Link to="/" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8">
          <ArrowLeft className="h-3.5 w-3.5" /> Back
        </Link>

        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: April 22, 2026</p>

        <div className="prose prose-sm prose-neutral dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-lg font-semibold mb-3">1. Agreement</h2>
            <p className="text-muted-foreground leading-relaxed">
              By creating an account or using Yours ("the Service"), you agree to these Terms of Service and
              our <Link to="/privacy" className="text-foreground underline underline-offset-2">Privacy Policy</Link>.
              If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">2. What Yours Provides</h2>
            <p className="text-muted-foreground leading-relaxed">
              Yours generates a personalized daily audio briefing based on your preferences, connected accounts, and
              selected news sources. The briefing is produced by AI and is intended for informational and entertainment
              purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">3. Your Account</h2>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1 leading-relaxed">
              <li>You must provide a valid email address to create an account.</li>
              <li>You are responsible for maintaining the security of your account.</li>
              <li>You may not share your account or use the Service on behalf of others without their consent.</li>
              <li>You must be at least 13 years old to use Yours.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">4. Connected Accounts (Gmail, Calendar)</h2>
            <p className="text-muted-foreground leading-relaxed">
              You may optionally connect your Google account to include email highlights and calendar events in your
              briefing. By connecting:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1 leading-relaxed">
              <li>You grant us read-only access to Gmail and Google Calendar as described in our Privacy Policy.</li>
              <li>We access only the minimum data needed to generate your briefing (subject lines, event titles and times).</li>
              <li>We do not store your emails or calendar events — they are processed in memory and discarded after briefing generation.</li>
              <li>You can disconnect at any time from Settings, which immediately revokes our access and deletes stored tokens.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">5. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">
              Briefings are generated by artificial intelligence. While we strive for accuracy:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1 leading-relaxed">
              <li>AI-generated content may contain errors, omissions, or inaccuracies.</li>
              <li>Briefings are not a substitute for reading primary sources, professional advice, or official communications.</li>
              <li>News summaries reflect the sources you selected and may not represent all perspectives.</li>
              <li>We are not responsible for decisions you make based on briefing content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">6. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1 leading-relaxed">
              <li>Use the Service to violate any law or regulation</li>
              <li>Redistribute, resell, or publicly broadcast generated briefings for commercial purposes</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Service or its APIs</li>
              <li>Interfere with the Service's operation or other users' access</li>
              <li>Create multiple accounts to circumvent limits</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">7. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Yours name, logo, and app design are our property. Generated briefings are created for your personal
              use. News content referenced in briefings belongs to the original publishers — we provide summaries and
              links, not full reproductions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">8. Service Availability</h2>
            <p className="text-muted-foreground leading-relaxed">
              We aim to deliver your briefing every day at your chosen time, but we do not guarantee uninterrupted
              service. Briefings may be delayed or unavailable due to third-party API outages, maintenance, or
              technical issues. We will make reasonable efforts to restore service promptly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">9. Pricing and Payments</h2>
            <p className="text-muted-foreground leading-relaxed">
              Yours is currently free during beta. If we introduce paid plans in the future, we will notify you in
              advance and you will not be charged without explicit consent. You may cancel at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">10. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              Yours is provided "as is" without warranties of any kind. To the maximum extent permitted by law, we
              are not liable for any indirect, incidental, or consequential damages arising from your use of the
              Service. Our total liability is limited to the amount you paid us in the 12 months preceding the claim
              (or $0 during the free beta period).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">11. Account Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              You may delete your account at any time. We may suspend or terminate accounts that violate these terms.
              Upon termination, we will delete your data in accordance with our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">12. Changes to These Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these terms from time to time. Material changes will be communicated via email or in-app
              notice at least 30 days before taking effect. Continued use after the effective date constitutes
              acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">13. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These terms are governed by the laws of the Commonwealth of Virginia, United States. Any disputes will
              be resolved in the courts of Fairfax County, Virginia.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">14. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              Questions about these terms? Email us at{" "}
              <a href="mailto:legal@yours.fm" className="text-foreground underline underline-offset-2">legal@yours.fm</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
